# Generated by Django 5.2 on 2025-05-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petroleum_name', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
                ('delivery_code', models.CharField(max_length=50, unique=True)),
                ('date_deliver', models.DateField()),
                ('total_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
