# Generated by Django 5.2 on 2025-05-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_deliveryhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.AlterModelOptions(
            name='deliveryhistory',
            options={'ordering': ['-date_deliver'], 'verbose_name': 'Delivery', 'verbose_name_plural': 'Deliveries'},
        ),
        migrations.AddField(
            model_name='deliveryhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
