# Generated by Django 5.2.1 on 2025-05-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_producttransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_number', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('Unleaded', 'Unleaded'), ('Diesel', 'Diesel'), ('Premium', 'Premium'), ('V-Power', 'V-Power'), ('XCS', 'XCS'), ('Xtra', 'Xtra'), ('Blaze', 'Blaze')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('liters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_liter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fuel Transaction',
                'verbose_name_plural': 'Fuel Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
