# Generated by Django 5.2 on 2025-05-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_remove_fueltransaction_stock_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fueltransaction',
            options={},
        ),
        migrations.AlterField(
            model_name='fueltransaction',
            name='fuel_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fueltransaction',
            name='machine_number',
            field=models.IntegerField(),
        ),
    ]
