# Generated by Django 5.2 on 2025-05-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_fueltransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueltransaction',
            name='liters',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fueltransaction',
            name='price_per_liter',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
