# Generated by Django 5.2.1 on 2025-05-23 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_fueltransaction_liters_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fueltransaction',
            options={'ordering': ['-created_at']},
        ),
    ]
